# tomcat配置
server:
  port: 8882
spring:
  profiles:
    include: common
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
    timeout: 5s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://cdb-m0meojov.gz.tencentcdb.com:10036/shop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: shop
    password: zx516130780
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 2
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true
#tomcat端口
tomcat:
  port: 8882
